"""Private browser-local report saving and read-only reopening.

Only an explicit Keep action writes storage. Saved strings are rendered with
textContent, never interpreted as document HTML or script.
"""
import json
from legal_pack_report import render_review_html,REVIEW_CSS

def render_report_exports(model=None):
    value={'id':model['report_id'],'model':model,'html':render_review_html(model,standalone=True),'json':json.dumps(model,ensure_ascii=False,indent=2)} if model else None
    payload=json.dumps(value,ensure_ascii=True).replace('<','\\u003c').replace('>','\\u003e').replace('&','\\u0026')
    return '''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>'''+REVIEW_CSS+'''
body{margin:0;font:14px/1.5 Arial,sans-serif;color:#183149;background:transparent}.exports{display:flex;gap:10px;flex-wrap:wrap;margin:12px 0}a,button,select{font:inherit;max-width:100%;background:#fff;border:1px solid #94a7b6;border-radius:7px;color:#183149;padding:10px 13px}a{display:inline-block;text-decoration:none;font-weight:600}button{cursor:pointer}a:hover,button:hover{border-color:#00665f;background:#eef8f5}.note{font-size:13px;color:#526475}#status{color:#125057;font-weight:600}#saved-report{margin-top:18px}select{width:100%}@media(max-width:560px){.exports>*{flex:1 1 100%;text-align:center}}
</style></head><body><div id="current" hidden><div class="exports"><a id="readable">Download readable report (HTML)</a><a id="saved">Save report to reopen (JSON)</a><button id="keep" type="button">Keep report on this device</button></div></div><details id="library"><summary><b>Reports kept on this device</b></summary><p class="note">Private to this browser profile, not your account. Anyone using this profile can open them. Up to five reports; clearing site data removes them. Keep downloaded copies for longer-term records.</p><label for="reports">Choose a saved report</label><select id="reports"></select><div class="exports"><button id="open" type="button">Open kept report</button><button id="remove" type="button">Remove kept copy</button><button id="close" type="button" hidden>Close saved view</button></div></details><p id="status" role="status"></p><div id="saved-report"></div><script>
const current='''+payload+''';
const storageKey='auction-sniper-private-reports-v2';
const byId=id=>document.getElementById(id);const status=text=>byId('status').textContent=text;
function read(){try{const x=JSON.parse(localStorage.getItem(storageKey)||'[]');return Array.isArray(x)?x.filter(m=>m&&m.schema_version==='2.0'&&/^[a-f0-9]{16}$/.test(m.report_id)).slice(0,5):[];}catch(e){status('Device storage is unavailable. Use a downloaded report instead.');return [];}}
function refresh(){const select=byId('reports');select.replaceChildren();const rows=read();if(!rows.length){const o=document.createElement('option');o.textContent='No reports kept on this device';select.append(o);}for(const m of rows){const o=document.createElement('option');o.value=m.report_id;o.textContent=m.property+' · '+String(m.created_at).slice(0,10);select.append(o);}byId('open').disabled=byId('remove').disabled=!rows.length;}
function node(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=String(text);if(cls)e.className=cls;return e;}
function heading(parent,text){parent.append(node('h2',text));}
function finding(f){const box=node('article',undefined,'dd-finding '+(f.severity==='CRITICAL / RED FLAG'?'critical':f.severity==='NEEDS CHECKING'?'check':'information'));box.append(node('span',f.severity,'dd-badge'),node('h3',f.title),node('p',f.summary),node('p','Action: '+f.action,'dd-action'));const evidence=node('details');evidence.append(node('summary','Source evidence'));for(const e of f.evidence||[]){evidence.append(node('p',e.document+(e.page?' · PDF page '+e.page:'')+(e.ocr?' · OCR: check original':''),'dd-source'),node('blockquote',e.excerpt));}box.append(evidence);return box;}
function list(parent,values){const ul=node('ul');for(const text of values||[])ul.append(node('li',text));parent.append(ul);}
function render(m){const host=byId('saved-report');host.replaceChildren();const box=node('article',undefined,'dd-report');box.append(node('p','SAVED AUCTION SNIPER REPORT','dd-kicker'),node('h1',m.property),node('p','Report '+m.report_id+' · '+m.created_at,'dd-muted'));heading(box,'Executive summary');box.append(node('p',m.summary));const cov=m.coverage||{};box.append(node('p',(cov.uploaded_files||cov.files)+' files · '+cov.pages+' pages · '+cov.ocr_pages+' OCR pages · '+cov.unread_pages+' pages with unread text'));box.append(node('p',m.disclaimer,'dd-callout'));heading(box,'Critical risks / red flags');for(const f of m.findings||[])if(f.severity==='CRITICAL / RED FLAG')box.append(finding(f));heading(box,'Key document observations');for(const f of m.observations||[])box.append(finding(f));heading(box,'Detailed findings');for(const s of m.sections||[]){const detail=node('details',undefined,'dd-topic');detail.append(node('summary',s.title+' · '+s.items.length+' findings'));for(const f of s.items)detail.append(finding(f));if(!s.items.length)detail.append(node('p',s.empty));box.append(detail);}heading(box,'Missing documents and evidence');list(box,m.missing);heading(box,'Contradictions / uncertainties');for(const u of m.uncertainties||[])box.append(node('h3',u.title),node('p',u.text),node('p',(u.sources||[]).join('; '),'dd-source'));for(const i of m.issues||[])box.append(node('p',i.document+': '+i.message,'dd-callout'));heading(box,'Questions for your solicitor');list(box,(m.questions||[]).map(q=>q.topic+': '+q.question));heading(box,'Document register');for(const d of m.documents||[])box.append(node('h3',d.document),node('p',d.pages+' pages · '+d.status),node('code',d.sha256));host.append(box);byId('close').hidden=false;}
if(current){byId('current').hidden=false;for(const [id,kind,mime] of [['readable','html','text/html;charset=utf-8'],['saved','json','application/json']]){const link=byId(id);link.href=URL.createObjectURL(new Blob([current[kind]],{type:mime}));link.download='auction-sniper-'+current.id+'.'+kind;}
byId('keep').onclick=()=>{try{const rows=read().filter(m=>m.report_id!==current.id);rows.unshift(current.model);if(rows.length>5){status('Five reports are already kept. Remove an older copy or download this report.');return;}localStorage.setItem(storageKey,JSON.stringify(rows));refresh();byId('library').open=true;status('Report kept on this device. You can return to this workspace and open it without processing the pack again.');}catch(e){status('This browser could not keep the report. Use a downloaded copy.');}};}
byId('open').onclick=()=>{const m=read().find(x=>x.report_id===byId('reports').value);if(m){try{render(m);status('Saved report reopened. It reflects the documents and date shown, not subsequent pack updates.');}catch(e){status('This saved copy is incomplete. Reopen a downloaded JSON report instead.');}}};
byId('remove').onclick=()=>{try{localStorage.setItem(storageKey,JSON.stringify(read().filter(x=>x.report_id!==byId('reports').value)));refresh();byId('saved-report').replaceChildren();byId('close').hidden=true;status('Kept copy removed from this browser. Downloaded copies are unaffected.');}catch(e){status('The kept copy could not be removed.');}};
byId('close').onclick=()=>{byId('saved-report').replaceChildren();byId('close').hidden=true;status('Saved view closed. The kept report remains available.');};window.addEventListener('storage',refresh);refresh();
</script></body></html>'''
