"""Plain-language definitions, independent of any property's legal terms."""
REVIEWED = '28 September 2026'
SOURCES = [
    ('Auction prices and buying', 'https://www.rics.org/content/dam/ricsglobal/documents/to-be-sorted/RICS-property-auctions-consumer-guide.pdf'),
    ('Commercial lease terms', 'https://ww3.rics.org/uk/en/journals/property-journal/lease-terms-apc.html'),
    ('Repairing obligations', 'https://ww3.rics.org/uk/en/journals/property-journal/an-a-z-of-repair-for-apc.html'),
    ('Leasehold ownership', 'https://www.gov.uk/leasehold-property'),
    ('Title information and plans', 'https://www.gov.uk/search-property-information-land-registry'),
    ('Business rates', 'https://www.gov.uk/introduction-to-business-rates'),
    ('Rateable value', 'https://www.gov.uk/guidance/how-non-domestic-property-including-plant-and-machinery-is-valued'),
    ('Commercial EPCs', 'https://www.gov.uk/energy-performance-certificate-commercial-property'),
    ('Option to Tax', 'https://www.gov.uk/guidance/opting-to-tax-land-and-buildings-notice-742a'),
    ('TOGC', 'https://www.gov.uk/guidance/transfer-a-business-as-a-going-concern-and-vat-notice-7009'),
]

# ID, title, explanation. Stable IDs support contextual help and external links.
GROUPS = [
('income-prices', 'Income, prices and yield', [
('giy', 'GIY / Gross Initial Yield', 'Current annual rent divided by price, multiplied by 100. On Auction Sniper, GIY at guide uses the lower guide price. For example, £20,000 current annual rent ÷ £200,000 guide = 10%. It excludes fees, tax, repairs, voids and financing. A higher GIY is not proof of a better investment. An explicit minimum excludes unknown yields.'),
('guide-price', 'Guide Price', 'The auctioneer’s published price indication, which can change before the auction. It is not a valuation or a promise of the selling price. Check the latest lot page and addendum.'),
('guide-range', 'Guide Price Range', 'A guide expressed as a lower and upper amount. Auction Sniper preserves both ends. Price filters use the lower end; a displayed yield range shows how yield changes across the guide. Bidding and the eventual price may exceed the range.'),
('reserve-price', 'Reserve Price', 'The seller’s minimum acceptable auction price, usually confidential. It is distinct from the guide. Read the auctioneer’s explanation of how guides and reserves relate for that sale.'),
('passing-rent', 'Passing Rent / Current Rent', 'The rent currently payable under the relevant letting arrangements, before ownership costs. It is not necessarily cash actually received: arrears, concessions and rent-free periods need checking. Confirm the rent schedule against the lease and payment history.'),
('historic-rent', 'Historic / Previous Rent', 'Rent from an earlier letting or period. A now-vacant property may have substantial historic rent but no current rental income. Auction Sniper keeps historic rent separate and does not use it to calculate current GIY.'),
('erv', 'ERV / Estimated Rental Value', 'An estimate of achievable market rent on stated letting assumptions. It is not a signed lease or guaranteed income. Look for recent comparable lettings, the proposed lease terms, incentives and the time and cost of reletting.'),
('net-yield', 'Net Yield', 'A yield after specified costs, unlike gross yield. Definitions vary: check which acquisition and running costs are included. Neither a guide GIY nor a target purchase price is automatically a net return.'),
('target-yield', 'Target Yield', 'Your desired gross return used to explore a purchase price: current annual rent ÷ target yield as a decimal. This is a scenario, not an appraisal. Acquisition costs and changes in rent can materially change the outcome.'),
('arrears', 'Arrears', 'Amounts due but unpaid, such as rent, service charge or insurance contributions. An occupied property can still have arrears. Ask for a dated payment ledger and clarify who receives or bears pre-completion debts.'),
]),
('ownership-leases', 'Ownership and leases', [
('freehold', 'Freehold', 'Ownership of the land and buildings without a lease expiry date in England and Wales. It can still be subject to occupational leases, charges, covenants and shared costs. The title and sale extent matter more than the label.'),
('leasehold', 'Leasehold', 'A right to hold property for the period and on the terms in a lease. Check the remaining term, ground rent, restrictions, service charges and repair obligations. Buying a leasehold interest is different from buying the landlord’s freehold.'),
('virtual-freehold', 'Virtual Freehold', 'A marketing description often used for a very long lease, rather than a separate legal tenure. It remains leasehold. Check the actual remaining term, rent, service charge, restrictions and rights before treating it as equivalent to freehold ownership.'),
('lease-term', 'Lease Term / Lease Expiry', 'The contractual duration and end date of a lease. The original term is not the same as the term remaining. Continued occupation after expiry does not by itself establish a new fixed-term lease; check the renewal and statutory position.'),
('tenant-break', 'Tenant Break', 'A contractual right allowing a tenant to end a lease early if the notice and other conditions are met. Record the break date, notice deadline and conditions. A lease advertised as ten years may provide much less secure income.'),
('rent-review', 'Rent Review', 'The lease mechanism for changing rent, such as an open-market review, index linkage or fixed increases. Check timing, assumptions, caps, collars and whether rent can fall. An upcoming review does not guarantee a rent increase.'),
('fri', 'FRI / Full Repairing and Insuring', 'A description of a lease intended to place repair and insurance costs on the tenant, directly or through reimbursement. The landlord may still arrange insurance or repair shared areas. The demise, exclusions and recovery clauses determine the actual exposure.'),
('iri', 'IRI / Internal Repairing and Insuring', 'A description generally limiting the tenant’s repairing obligation to the interior, with an insurance obligation or contribution. External and structural costs may remain with the landlord. Read the actual lease rather than relying on the abbreviation.'),
('covenant', 'Covenant / Tenant Covenant Strength', 'A covenant is a binding promise or obligation. In investment discussions, tenant covenant strength means the tenant’s ability to meet its obligations. A familiar trading brand is not necessarily the legal tenant or a parent-company guarantee.'),
('vacant-possession', 'Vacant Possession', 'A sale or handover requirement concerning possession without occupiers and relevant obstructions or interests. It is not a promise of good condition or immediate lettability. Your solicitor must check the exact contractual requirement and any retained rights.'),
('ground-rent', 'Ground Rent', 'Rent paid under a headlease or long lease to the superior landlord. It is separate from occupational income and service charge. Check review provisions and payment obligations throughout the remaining lease term.'),
('peppercorn', 'Peppercorn Rent', 'A nominal rent, commonly used where no meaningful monetary ground rent is intended. It does not mean there are no service charges, insurance contributions or other lease liabilities.'),
('service-charge', 'Service Charge', 'A contribution towards services or shared building or estate costs. Check the lease, apportionment, budget, accounts, caps and major works. Landlord costs are not always fully recoverable from occupational tenants.'),
('dilapidations', 'Dilapidations / Schedule of Condition', 'Dilapidations concern breaches of a tenant’s repair and related lease obligations. A schedule of condition records condition and may limit liability if the lease incorporates it appropriately. Neither automatically guarantees that a tenant will fund refurbishment.'),
('security-of-tenure', 'Security of Tenure / Contracted Out', 'In England and Wales, qualifying business tenancies may have renewal protection under the Landlord and Tenant Act 1954. A properly contracted-out lease excludes that protection. Scotland and Northern Ireland have different legal systems; confirm the applicable regime.'),
]),
('costs-compliance', 'Tax, rates and compliance', [
('rateable-value', 'Rateable Value / RV', 'The valuation used as a starting point for calculating business rates. It is not the rates bill, current rent or ERV. Check the assessment, valuation date and applicable national system.'),
('business-rates', 'Business Rates', 'A tax on most non-domestic premises. The bill depends on valuation, the applicable multiplier or rate and reliefs. Occupied and empty-property liabilities differ, and rules vary across the UK. Do not assume a vacant shop has no rates cost.'),
('epc', 'EPC / Energy Performance Certificate', 'A certificate assessing a building’s energy performance. Check its rating, validity, address and coverage: a shop and flats may need separate certificates. The EPC does not replace a condition survey.'),
('mees', 'MEES / Minimum Energy Efficiency Standards', 'Energy-efficiency rules that can restrict letting certain property unless requirements or exemptions are met. Scope and rules differ by jurisdiction and property type. Check current official guidance and budget for any evidenced improvement work.'),
('vat', 'VAT / Value Added Tax', 'A tax that may apply to the property price, rent or professional and auction fees. Each can have different treatment. Check whether quoted amounts include VAT and whether it is recoverable for your circumstances.'),
('option-to-tax', 'Option to Tax', 'A VAT election affecting certain supplies of land and buildings, subject to exceptions. A seller’s option does not simply transfer to the buyer. Obtain the evidence and confirm your own VAT position before exchange or bidding.'),
('togc', 'TOGC / Transfer of a Going Concern', 'VAT treatment under which a qualifying business transfer is not treated as a supply for VAT purposes. A let-property sale can qualify only if the relevant conditions are met. It is not an automatic exemption because a tenant is present or a buyer is VAT-registered.'),
]),
('auction-documents', 'Auction documents, process and status', [
('legal-pack', 'Legal Pack', 'The seller’s auction documents, which may include title, leases, searches and sale conditions. Contents vary and can change. View or download obtains the source documents; Analyse Legal Pack organises the supplied evidence and issues requiring professional review.'),
('special-conditions', 'Special Conditions of Sale', 'Terms applying specifically to a lot which can alter the general auction conditions. Check completion, deposits, extra costs, VAT, title obligations and remedies. Do not assume the general conditions alone describe the purchase.'),
('buyers-fee', 'Buyer’s Premium / Admin Fee', 'An additional auctioneer charge which may be fixed, percentage-based or subject to a minimum, with VAT included or added. Auction Sniper’s estimate is based on the guide and evidenced tariff. The lot’s actual terms take precedence.'),
('auction-deposit', 'Auction Deposit', 'An amount payable under the sale terms, commonly on exchange in a traditional auction. It normally forms part of the purchase price, rather than an additional fee. Confirm the required amount, minimum, payment deadline and consequences of default.'),
('completion', 'Exchange / Completion', 'Exchange generally creates the binding purchase contract; completion transfers the money and property under its terms. Traditional and conditional auction methods can differ. Never assume a standard completion period without reading the lot conditions.'),
('addendum', 'Addendum', 'A correction or update issued after the original particulars or pack. It can change price, tenancy information or contract terms. Check for the latest version before bidding and keep a dated copy.'),
('title-register', 'Title Register / Title Plan', 'The register records the registered ownership and relevant entries; the plan shows the registered extent subject to its limitations. A title plan usually shows general boundaries. Compare all titles, leases and transfer plans with the property actually being sold.'),
('easement', 'Easement / Restrictive Covenant', 'An easement may grant rights such as access or drainage. A restrictive covenant may limit how land is used. Their existence, extent and enforceability require title-specific legal review.'),
('searches', 'Searches / CPSE Replies', 'Searches report matters within a provider’s defined scope, such as local authority, drainage or environmental information. CPSE replies are the seller’s responses to commercial property enquiries. Check dates, qualifications, unanswered questions and referenced documents.'),
('sold-prior', 'Sold Prior', 'The auctioneer reports that the lot sold before the scheduled auction. A result may not disclose a price. Auction Sniper retains the appearance and status rather than silently removing its history.'),
('withdrawn', 'Withdrawn', 'The lot was removed from that sale. This does not establish whether it sold privately, why it was withdrawn or whether it will return.'),
('postponed', 'Postponed', 'The auction or lot has been deferred. A replacement date may be unknown. Check the source before treating an older date as current.'),
('mixed-use', 'Mixed Use', 'A property containing more than one type of use, commonly a commercial unit with residential accommodation. Check each part’s tenure, occupation, income and costs. Mixed-use is accepted on Auction Sniper’s commercial board.'),
('stp', 'Development Potential / STP', 'STP means subject to planning permission. Development potential is a possibility, not consent or guaranteed profit. Verify permission, conditions, title restrictions, access, services, occupation and delivery costs before relying on an alternative use.'),
])]
